name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install dependencies
      run: yarn install
    - name: Install ESLint CLI
      run: yarn global add eslint
    - name: Run ESLint
      run: eslint "src/**/*.ts" "src/**/*.vue"
