name: Publish app on macOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn install
      - name: Build application for ${{ matrix.os }}
        run: yarn run build:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: true
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
