name: Publish app

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - if: matrix.os == 'windows-latest'
        run: |
          cd patches
          TYPE better-sqlite3+7.0.1.patch | MORE /P > better-sqlite3+7.0.1.patch
          TYPE bindings+1.5.0.patch | MORE /P > bindings+1.5.0.patch
          cd ..
        shell: cmd
      - name: Install dependencies
        run: npm install
      - name: Patch dependencies
        run: npx patch-package
      - name: Build application for ${{ matrix.os }}
        run: npm run electron:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
