name: Publish app on Linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn install
      - name: Build application for ${{ matrix.os }}
        run: yarn run build:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
