name: Publish app on macOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install packages
        run: npm install--force
      - name: Build application for ${{ matrix.os }}
        run: npm run electron:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # temporary disabled notarization
          CSC_IDENTITY_AUTO_DISCOVERY: false
#          CSC_LINK: ${{ secrets.mac_certs }}
#          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
